Ext.define('mdaapp.model.RuleFilter', {
    extend: 'Ext.data.Model',

    fields: [
        {name: 'filterId', type: 'int'},
        {name: 'colId', type: 'int'},
        {name: 'opsql', type: 'string'},
        {name: 'place', type: 'string'},
        {name: 'optitle', type: 'string'},
        {name: 'description', type: 'string'},
        {name: 'showdescription', type: 'int'},
        {name: 'creator', type: 'string'},
        {name: 'createtime', type: 'string'},
        {name: 'op1label', type: 'string'},
        {name: 'op1candidate', type: 'string'},
        {name: 'showoperator1', type: 'boolean'},
        {name: 'param1leftlabel', type: 'string'},
        {name: 'param1style', type: 'string'},
        {name: 'param1rightlabel', type: 'string'},
        {name: 'opconnectorid', type: 'int'},
        {name: 'connectorcandidate', type: 'string'},
        {name: 'paramcount', type: 'int'},
        {name: 'op2label', type: 'string'},
        {name: 'op2candidate', type: 'string'},
        {name: 'showoperator2', type: 'boolean'},
        {name: 'param2leftlabel', type: 'string'},
        {name: 'param2style', type: 'string'},
        {name: 'param2rightlabel', type: 'string'},
        {name: 'param1checkrule', type: 'string'},
        {name: 'param2checkrule', type: 'string'},
        {name: 'paramscheckrule', type: 'string'},
        {name: 'resultoperatorid', type: 'int'},
        {name: 'op1Id', type: 'int'},
        {name: 'op2Id', type: 'int'},
        {name: 'param1value', type: 'string'},
        {name: 'param2value', type: 'string'},
        {name: 'outputtitle', type: 'string'},
        {name: "ruleId", type: 'int'},
        {name: "jobid", type: 'int'},
        {name: "isdistinct", type: 'int'},
        {name: "ordernum", type: 'int'},
        {name: "param1type", type: 'string'},
        {name: "param2type", type: 'string'},
        {name: "outputtitle", type: 'string'},
        {name: "windowx", type: 'int'},
        {name: "windowy", type: 'int'},
        {name: "showConnector", type: 'boolean'}

    ]
});
